In [1]:
import sys
sys.path.append('../')

In [2]:
import torch 
from tabnet.criterions import TabNetPretrainingLoss
from tabnet.core._models import BinaryMasker

In [3]:
SAMPLE_SIZE = 1024
BATCH_SIZE = 256
FEATS_DIMS = 27
MASK_RATE = 0.2

## Prepare testing data

In [4]:
total_X = torch.randn((SAMPLE_SIZE, FEATS_DIMS))
batch_X = total_X[:BATCH_SIZE, ...]

masker = BinaryMasker(MASK_RATE)
batch_y, mask = masker(batch_X)

population_std = torch.std(total_X, dim=0)
print('population_std : ', population_std.size())
print('batch_y : ', batch_y.size())

population_std :  torch.Size([27])
batch_y :  torch.Size([256, 27])


## Initial the loss objects

In [5]:
loss_with_populatioin_std = TabNetPretrainingLoss(population_std=population_std, epsilon=1e-9)
loss_without_populatioin_std = TabNetPretrainingLoss(population_std=None, epsilon=1e-9)

## Get loss values

In [6]:
float(loss_with_populatioin_std(batch_X, batch_y, mask=mask))

1472.071044921875

In [7]:
float(loss_without_populatioin_std(batch_X, batch_y, mask=mask))

1.3877619504928589

In [8]:
population_std

tensor([1.0119, 0.9762, 1.0003, 0.9929, 1.0172, 0.9886, 1.0076, 0.9972, 0.9628,
        1.0399, 1.0193, 1.0191, 0.9970, 0.9990, 0.9877, 1.0130, 1.0084, 0.9936,
        1.0133, 0.9975, 0.9618, 0.9958, 1.0002, 0.9737, 0.9630, 0.9966, 1.0149])

In [11]:
batch_y[0, ...]

tensor([ 0.0000,  0.0000, -0.0000, -1.2544, -1.9488, -1.4081,  0.0000,  0.0000,
        -2.0185, -0.8474, -0.4314,  0.7451, -0.6564, -0.0000, -0.6916,  1.5124,
        -0.7502, -2.0825,  0.0000, -0.1168,  0.0000,  1.1331, -1.9027, -0.0000,
        -0.0000, -0.5119, -0.8376])

In [12]:
mask[0, ...]

tensor([1., 1., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        1., 0., 1., 0., 0., 1., 1., 0., 0.])